import React, { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Layout, PageHeader, LoadingSpinner, Card, Modal, EmptyState } from '../../components/Layout';
import { invoiceApi } from '../../services/api';
import type { Invoice } from '../../types';
import { Receipt, FileText } from 'lucide-react';

export default function RetailerInvoices() {
  const [selectedInvoice, setSelectedInvoice] = useState<Invoice | null>(null);

  const { data: invoices, isLoading } = useQuery({
    queryKey: ['my-invoices'],
    queryFn: () => invoiceApi.getMy(),
  });

  if (isLoading) return <Layout><LoadingSpinner /></Layout>;

  const invoiceList = invoices?.data || [];

  return (
    <Layout>
      <PageHeader
        title="My Invoices"
        subtitle="View your B2B invoices - generated by Admin after GRN confirmation"
      />

      {invoiceList.length === 0 ? (
        <Card>
          <EmptyState
            icon={Receipt}
            title="No Invoices"
            description="Invoices will appear here after Admin generates them from your confirmed GRNs."
          />
        </Card>
      ) : (
        <Card className="overflow-hidden p-0">
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead className="bg-dark-800">
                <tr>
                  <th>Invoice #</th>
                  <th>GRN #</th>
                  <th>Subtotal</th>
                  <th>Tax</th>
                  <th>Total</th>
                  <th>Type</th>
                  <th>Date</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-dark-700">
                {invoiceList.map((invoice) => (
                  <tr key={invoice.id} className="hover:bg-dark-800/50">
                    <td className="font-medium text-white">{invoice.invoiceNumber}</td>
                    <td>{invoice.grnNumber}</td>
                    <td>₹{invoice.subtotal.toFixed(2)}</td>
                    <td>
                      {invoice.isInterstate
                        ? `₹${invoice.igst?.toFixed(2)}`
                        : `₹${((invoice.cgst || 0) + (invoice.sgst || 0)).toFixed(2)}`}
                    </td>
                    <td className="font-medium text-primary-500">₹{invoice.totalAmount.toFixed(2)}</td>
                    <td>
                      <span className={`badge ${invoice.isInterstate ? 'badge-info' : 'badge-success'}`}>
                        {invoice.isInterstate ? 'IGST' : 'CGST/SGST'}
                      </span>
                    </td>
                    <td>{new Date(invoice.createdAt).toLocaleDateString()}</td>
                    <td>
                      <button
                        onClick={() => setSelectedInvoice(invoice)}
                        className="btn btn-secondary btn-sm"
                      >
                        View
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </Card>
      )}

      {/* Invoice Detail Modal */}
      {selectedInvoice && (
        <Modal isOpen={true} onClose={() => setSelectedInvoice(null)} title={`Invoice ${selectedInvoice.invoiceNumber}`}>
          <div className="space-y-4">
            {/* Header */}
            <div className="bg-dark-800 rounded-lg p-4">
              <div className="grid grid-cols-2 gap-4 text-sm">
                <div>
                  <span className="text-dark-400">GRN:</span>
                  <span className="ml-2 text-white">{selectedInvoice.grnNumber}</span>
                </div>
                <div>
                  <span className="text-dark-400">Date:</span>
                  <span className="ml-2 text-white">{new Date(selectedInvoice.createdAt).toLocaleString()}</span>
                </div>
              </div>
            </div>

            {/* Items */}
            <div>
              <h4 className="font-medium text-white mb-2">Items</h4>
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead className="bg-dark-800">
                    <tr>
                      <th className="text-left">Material</th>
                      <th>HSN</th>
                      <th>Qty</th>
                      <th>Amount</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-dark-700">
                    {selectedInvoice.items.map((item) => (
                      <tr key={item.id}>
                        <td className="text-white">{item.materialName}</td>
                        <td className="text-center">{item.hsnCode}</td>
                        <td className="text-center">{item.packets} pkt</td>
                        <td className="text-right">₹{item.lineTotal.toFixed(2)}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>

            {/* Totals */}
            <div className="bg-dark-800 rounded-lg p-4">
              <div className="space-y-2 text-sm">
                <div className="flex justify-between">
                  <span className="text-dark-400">Subtotal:</span>
                  <span className="text-white">₹{selectedInvoice.subtotal.toFixed(2)}</span>
                </div>
                {selectedInvoice.isInterstate ? (
                  <div className="flex justify-between">
                    <span className="text-dark-400">IGST:</span>
                    <span className="text-white">₹{selectedInvoice.igst?.toFixed(2)}</span>
                  </div>
                ) : (
                  <>
                    <div className="flex justify-between">
                      <span className="text-dark-400">CGST:</span>
                      <span className="text-white">₹{selectedInvoice.cgst?.toFixed(2)}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-dark-400">SGST:</span>
                      <span className="text-white">₹{selectedInvoice.sgst?.toFixed(2)}</span>
                    </div>
                  </>
                )}
                <div className="flex justify-between pt-2 border-t border-dark-600">
                  <span className="font-medium text-white">Total:</span>
                  <span className="font-bold text-primary-500">₹{selectedInvoice.totalAmount.toFixed(2)}</span>
                </div>
              </div>
            </div>

            <button onClick={() => setSelectedInvoice(null)} className="btn btn-secondary w-full">
              Close
            </button>
          </div>
        </Modal>
      )}
    </Layout>
  );
}